// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR97ZMGZPLYUZ2oafAOVKJeGPuo-y-5Ck',
    appId: '1:701775304238:web:cd5da7102021a93a3771bf',
    messagingSenderId: '701775304238',
    projectId: 'flutter-rental-64301',
    authDomain: 'flutter-rental-64301.firebaseapp.com',
    storageBucket: 'flutter-rental-64301.appspot.com',
    measurementId: 'G-QGY09FLM36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFl1e8S0oapDLGEa6J7sUc8Z7VMOXJn1Y',
    appId: '1:701775304238:android:b69eba117a038b863771bf',
    messagingSenderId: '701775304238',
    projectId: 'flutter-rental-64301',
    storageBucket: 'flutter-rental-64301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYW-coyWXPtwSM2InOZXNUSoaetVDehQ',
    appId: '1:701775304238:ios:0df738df50b5ece23771bf',
    messagingSenderId: '701775304238',
    projectId: 'flutter-rental-64301',
    storageBucket: 'flutter-rental-64301.appspot.com',
    iosBundleId: 'com.example.flutterRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTYW-coyWXPtwSM2InOZXNUSoaetVDehQ',
    appId: '1:701775304238:ios:0df738df50b5ece23771bf',
    messagingSenderId: '701775304238',
    projectId: 'flutter-rental-64301',
    storageBucket: 'flutter-rental-64301.appspot.com',
    iosBundleId: 'com.example.flutterRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR97ZMGZPLYUZ2oafAOVKJeGPuo-y-5Ck',
    appId: '1:701775304238:web:c25b9925a73a1fbc3771bf',
    messagingSenderId: '701775304238',
    projectId: 'flutter-rental-64301',
    authDomain: 'flutter-rental-64301.firebaseapp.com',
    storageBucket: 'flutter-rental-64301.appspot.com',
    measurementId: 'G-BZJ941KTCB',
  );
}
